### ISSUE TITLE
'MemorySize' value failed to satisfy constraint

### ISSUE THREAD

**Issue by nicholsn** [awslabs/genai-bedrock-agent-chatbot#4]
When deploying the stack to a new account, I received the following error. Updating the memory settings to `3008` resolved the issue for deployment, so just logging this here in case others run into this or perhaps the default settings could be updated.

```
chatbot-stack: creating CloudFormation changeset...
9:51:46 PM | CREATE_FAILED        | AWS::Lambda::Function                       | AgentActionLambdaFunction9B8BCF65
Resource handler returned message: "'MemorySize' value failed to satisfy constraint: Member must have value less than or equal to 3008 (Service: Lambda, Status Code: 400, Request ID: 4954a967-8967-4ad3-8539-a2252b
d16eb9)" (RequestToken: 88050a3b-9339-8469-e97e-0e164d43b9b9, HandlerErrorCode: InvalidRequest)


 ❌  chatbot-stack failed: Error: The stack named chatbot-stack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "'MemorySize' value failed to satisfy constraint: Member must have value less than or equal to 3008 (Service: Lambda, Status Code: 400, Request ID: 4954a967-8967-4ad3-8539-a2252bd16eb9)" (RequestToken: 88050a3b-9339-8469-e97e-0e164d43b9b9, HandlerErrorCode: InvalidRequest)
    at FullCloudFormationDeployment.monitorDeployment (/opt/homebrew/lib/node_modules/aws-cdk/lib/index.js:442:10568)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/opt/homebrew/lib/node_modules/aws-cdk/lib/index.js:445:199515)
    at async /opt/homebrew/lib/node_modules/aws-cdk/lib/index.js:445:181237

 ❌ Deployment failed: Error: The stack named chatbot-stack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "'MemorySize' value failed to satisfy constraint: Member must have value less than or equal to 3008 (Service: Lambda, Status Code: 400, Request ID: 4954a967-8967-4ad3-8539-a2252bd16eb9)" (RequestToken: 88050a3b-9339-8469-e97e-0e164d43b9b9, HandlerErrorCode: InvalidRequest)
    at FullCloudFormationDeployment.monitorDeployment (/opt/homebrew/lib/node_modules/aws-cdk/lib/index.js:442:10568)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/opt/homebrew/lib/node_modules/aws-cdk/lib/index.js:445:199515)
    at async /opt/homebrew/lib/node_modules/aws-cdk/lib/index.js:445:181237

The stack named chatbot-stack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "'MemorySize' value failed to satisfy constraint: Member must have value less than or equal to 3008 (Service: Lambda, Status Code: 400, Request ID: 4954a967-8967-4ad3-8539-a2252bd16eb9)" (RequestToken: 88050a3b-9339-8469-e97e-0e164d43b9b9, HandlerErrorCode: InvalidRequest)
```

**Comment by nicholsn** [comment]
Note that didn't actually work as I now have another error:

`"Invalid request provided: Create TaskDefinition: No Fargate configuration exists for given values: 2048 CPU, 3008 memory.`

I'll try downgrading the Fargate configuration to use cpu `512` and memory `2048` but that seems under resourced. 

It looks like new accounts are resource limited and I'll need to increase my quota or maybe that will be triggered automatically once this is deployed. 

https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html

**Comment by praveenflash** [comment]
you can try `2048` CPU and `4096` memory. That should satisfy your resource needs

**Comment by nicholsn** [comment]
Thanks, this ended up being a Quota limit on my account.  `512` CPU and `2048` worked but a little slow. Will switch back when my lambda quota is increased.
